### ISSUE TITLE
Feature Request: ability to find the latest upload of an app by bundle id

### ISSUE THREAD

**Issue by EkkoG** [significa/app-distribution-server#20]
> I do have a few doubts of this feature
> 
> 1. I'm don't think listing the a filesystem and opening all JSON files is a good idea. Specially using S3 this operation would be very costly, and probably not finish within usable time. (I can test this later on our production storage)
> 
> 2. This has some security implications. While the builds are protected from _directory listing_ with unique IDs in the URL, this will enable anyone with information about the name of the package to obtain access to the list of packages. An attacker could even be able to guess package names by brute forcing this route. This might not be an issue for you, but for us it is,
> 
> I do understand the feature, maybe a solution would be to make this configurable (enable/disable) or protected via an env var. Before implementing anything please consider leaving your feedback.

_Originally posted by @tofran in https://github.com/significa/app-distribution-server/pull/14#discussion_r1746353765_

**Comment by EkkoG** [comment]
It's bad to use `listdir` to implement this feature, it was thoughtless.

And I think we need to add a db if we want to implement this feature in a better way.

**Comment by tofran** [comment]
I don't think it was thoughtless, I thank you very much for the attempt in making that work.
I did test scanning the files on a copy of my production instance and it just takes forever, I couldn't even let it finish.

In order to make this work for most scenarios we do need some kind of index.

- It could be a full fledged RDMS - which I think is too much.
- It could be a simple SQLite database, that would sync to the filesystem, but even this brings another level of complexity to the project (ex Litestream).
- Alternatively we can try to index it in the filesystem in a cheeky way.
  - On AWS we can use ETag for optimistic locking and leveraging a shared index, while locally file locks solve the problem. The problem is that for this we cannot use pyfilesystem and need independent implementations for at least these two different storage backends.
    I'm not using this project to save files to the local filesystem, but I know it makes it easy for most people that just want a simple solution, hence why I went with pyfilesystem. I do think pyfilesystem has a pretty poor design for s3, and I am considering removing it, but I'm avoiding the hassle (I may create an issue on this)
  - Yet I see the possibility of using directory listings or similar to create an index.

**Comment by EkkoG** [comment]
I mean I was thoughtless in pr#14, not the problem you pointed out.😅

**Comment by tofran** [comment]
I have just made the simplest solution possible. I was over complicating because I was considering indexing all the uploads. It is entirely possible to do it, but requires removing pyfilesystem.

For now I just save the last upload, that's what you need and this way simplify the work for now.

**Comment by EkkoG** [comment]
- I see the code, I think it no need to store all data in pyfilesystem, store all data include index data in pyfilesytem limit ourself implement features in elegant way, I thinks pyfilesystem only need act as a file store backend, info data create by app can store in a `db` directory in local file system, these info include all info store in `BuildInfo` struct, and file exist info, for now when access a build it will always make a file access to pyfilesystem, when the directory is backend by system like s3, it will make some cost always, I thinks this pyfilesystem access is no necessary, we can ensure the file existence in local db, it's fast and not costly, check file in pyfilesystem can keep good consistency, this it good.
- This project want to keep things simple, but the implement is start complex now, like store data in txt files as a light db, mostly it because the lack of a local db, when only store a build id is not enought, we will create another txt file or json file, I thinks have a local db is more simple when implement features.
